enum SleepDataSource: String, CaseIterable {
  case appleHealthKit = "com.apple.health"
  case oura = "com.ouraring.oura"
  case withings = "com.withings.wiScaleNG"
  case whoop = "com.whoop.iphone"
  case garmin = "com.garmin.connect.mobile"
  case fitbit = "com.fitbit.FitbitMobile"
  case polar = "fi.polar.polarflow"
  case coros = "com.coros.coros"
  case suunto = "com.sports-tracker.suunto.iphone"
  case xiaomi = "com.xiaomi.miwatch.pro"
  case muse = "com.interaxon.muse"
  case biostrap = "com.biostrap.Biostrap"
  case cardiomood = "com.corsanohealth.cardiomood"
  case eightsleep = "com.eightsleep.Eight"
}
